### ISSUE TITLE
Endgame hall of fame displays last round acro 3 times

### ISSUE THREAD

**Issue by danielbergamin** [ckiely91/acrofever#17]
As per title

**Comment by ckiely91** [comment]
*Sort of* fixed for now. I made a recent change so that the status only changes to 'endofround' if it isn't actually the end of game. The method is prevented from running multiple times by checking that status. The status change was too far down which caused the end of round function to run multiple times.

I've changed it back to how it was before, but the side effect is that users will now see a flash of the 'end of round' screen even if it's the end of game (which is what I was trying to fix). Need to think about how better to approach this.
