### ISSUE TITLE
Allow users to join or leave mid-game

### ISSUE THREAD

**Issue by ckiely91** [ckiely91/acrofever#8]

**Comment by danielbergamin** [comment]
Ooh yes, this is probably the most important one. One way you might be able
to achieve this is moving the variable storing the number of active players
to the round scope, rather than being scoped to the entire game. A full
player list of all players past and present could still be stored against
the game, but this would only be used for game score display/endgame winner
calculation. All other invocations of game.players would move to the round
scope
